---
title: "Announcements, Fall 2024"
---

::: {.announcements}
# Thursday, December 5th

- Quizzes 3&4 before Thanksgiving
	- Quiz 3 was returned Tuesday, quiz 4 should be back today (95% graded)
	- Regrades only open for one week!
- Upcoming assignments
	- [PA5](../pa/pa5/index.html) is due this Friday, Dec 6th; the submission is open
- Office hours (reminder)
	- Prof Bloomfield Office Hours: Tue 1:00-2:30 and Thu 2:00-3:00 in Rice 402
	- Prof Pettit Office Hours: Mon 2:30-4:00 and Wed 1:30-3:00 in Rice 212
	- TA office hours: Sunday through Thursday from 5 pm to 9 pm
	- Sun/Tue/Thu in Rice 032, Mon/Wed in Rice 540
- OH during finals week TBA
- Final exam
  - Monday, December 16th, from 7-10
  - In Gilmer 301 (Pettit) and Rice 130 (Bloomfield)
- We are aiming to hold office hours during finals week; details TBA
- Today's lecture: finish [Reductions](reductions.html), go over ML part 2, then the course finale
	- Reminder: some slide sets are now in the [course repository](https://uva-cs.github.io/dsa2/)
:::



::: {.announcements}
# Tuesday, December 3rd

- Quizzes 3&4 before Thanksgiving
	- Quiz 3 will be returned today
	- Quiz 4 should be back on Thursday
	- Regrades only open for one week!
- Upcoming assignments
	- [PS9](../ps/ps9.pdf) is due tomorrow, Wednesday, Dec 4th
	- [PA5](../pa/pa5/index.html) is due Friday, Dec 6th
	  - The submission will open up by tomorrow
- Office hours (reminder)
	- Prof Bloomfield Office Hours: Tue 1:00-2:30 and Thu 2:00-3:00 in Rice 402
	- Prof Pettit Office Hours: Mon 2:30-4:00 and Wed 1:30-3:00 in Rice 212
	- TA office hours: Sunday through Thursday from 5 pm to 9 pm
	- Sun/Tue/Thu in Rice 032, Mon/Wed in Rice 540
- We are aiming to hold office hours during finals week; details TBA
- Today's lecture: continue with [Reductions](reductions.html)
	- Reminder: slide sets are now in the [course repository](https://uva-cs.github.io/dsa2/)
:::



::: {.announcements}
# Tuesday, November 19th

- Quizzes 3&4 this Thursday (Thu, 11/21)
	- Topic list and sample quizzes in Canvas' files
- Upcoming assignments
	- [PA4](../pa/pa4/index.html) is due Monday before Thanksgiving (11/25)
	- PS9 will be out late this week, and will be due the week *after* Thanksgiving (Wed, Dec 4th)
	- PA5 will be out late this week, and will be due the last day of classes (Fri, Dec 6th)
- Grading: [PS5](../ps/ps5.html) & [PS6](../ps/ps6.html) grades returned (in Gradescope); late penalty info in Canvas' Posted Feedback
	- Also grades for [PA2](../pa/pa2/index.html) & [PA3](../pa/pa3/index.html)
	- [PA3](../pa/pa3/index.html) is having a discussion about the test cases (Piazza post @319)
- Office hours (reminder)
	- Prof Bloomfield Office Hours: Tue 1:00-2:30 and Thu 2:00-3:00 in Rice 402
	- Prof Pettit Office Hours: Mon 2:30-4:00 and Wed 1:30-3:00 in Rice 212
	- TA office hours: Sunday through Thursday from 5 pm to 9 pm
	- Sun/Tue/Thu in Rice 032, Mon/Wed in Rice 540
	- No OH this Thursday (b/c of the quizzes), and none after next Monday
- Today's lecture: continue with [Reductions](reductions.html)
	- Reminder: slide sets are now in the [course repository](https://uva-cs.github.io/dsa2/)
:::



::: {.announcements}
# Tuesday, November 14th

- [PS8](../ps/ps8.html) was due yesterday (Wed, 11/13)
- No PS9 due next week because...
- Quizzes 3&4 next Thursday (Thu, 11/21)
	- We'll release a list of topics late this week
- [PA4](../pa/pa4/index.html) is due Monday before Thanksgiving (11/25)
- Grading: [PS5](../ps/ps5.html) & [PS6](../ps/ps6.html) grades returned (in Gradescope); late penalty info in Canvas' Posted Feedback
	- Also grades for [PA2](../pa/pa2/index.html) & [PA3](../pa/pa3/index.html)
- Schedule
	- Both PS9 and PA5 will be due the last week of class (Wed & Fri, respectively)
	- We'll get them out early so that you have time to procrastinate
- Office hours (reminder)
	- Prof Bloomfield Office Hours: Tue 1:00-2:30 and Thu 2:00-3:00 in Rice 402
	- Prof Pettit Office Hours: Mon 2:30-4:00 and Wed 1:30-3:00 in Rice 212
	- TA office hours: Sunday through Thursday from 5 pm to 9 pm
	- Sun/Tue/Thu in Rice 032, Mon/Wed in Rice 540
- Today's lecture: continue with [Reductions](reductions.html)
	- Reminder: slide sets are now in the [course repository](https://uva-cs.github.io/dsa2/)
:::



::: {.announcements}
# Tuesday, November 12th

- PS8 due tomorrow (Wed, 11/13)
- Quizzes 3&4 next week (Thu, 11/21)
	- We'll release a list of topics late this week
- PA4 was released last week, due Monday before Thanksgiving (11/25)
- Grading update
	- PS5 & PS6 grades should be back by the end of the week
- Schedule
	- Both PS9 and PA5 will be due the last week of class
	- We'll get them out early so that you have time to procrastinate
- Office hours (reminder)
	- Prof Bloomfield Office Hours: Tue 1:00-2:30 and Thu 2:00-3:00 in Rice 402
	- Prof Pettit Office Hours: Mon 2:30-4:00 and Wed 1:30-3:00 in Rice 212
	- TA office hours: Sunday through Thursday from 5 pm to 9 pm
	- Sun/Tue/Thu in Rice 032, Mon/Wed in Rice 540
- Today's lecture: finish [Dynamic Programming](dp.html), then start [Reductions](reductions.html)
:::




::: {.announcements}
# Thursday, November 7th

- PS7 due last night
- PS8 out late this week, will be on DP, due next Wed (11/13)
- Quizzes 3&4 the following week (Thu, 11/21)
- PA4 should be out today, due right before Thanksgiving
- Grading update
	- PS0, PS3, and PS4 have been returned
	- Regrades for the quizzes and PS3 & 4 will be opened until late this week
		- Use this responsibly!
	- PS5 & PS6 should be back soon
	- Still to grade: regrades
- Office hours (reminder)
	- Prof Bloomfield Office Hours: Tue 1:00-2:30 and Thu 2:00-3:00 in Rice 402
	- Prof Pettit Office Hours: Mon 2:30-4:00 and Wed 1:30-3:00 in Rice 212
	- TA office hours: Sunday through Thursday from 5 pm to 9 pm
	- Sun/Tue/Thu in Rice 032, Mon/Wed in Rice 540
- Today's lecture: [Dynamic Programming](dp.html), then onto [Reductions](reductions.html)
:::



::: {.announcements}
# Halloween!!! Thursday, October 31st

- PS6 due last night
- PS7 out late this week, will be on DP, due next Wed
- PA3 out, due this Fri, Nov 1st
- No lecture (or office hours) next Tuesday, Nov 5th
- Grading update
	- PS0, PS3, and PS4 have been returned
	- Regrades for the quizzes and PS3 & 4 will be opened until late this week
		- Use this responsibly!
	- Still to grade: regrades
- Office hours (reminder)
	- Prof Bloomfield Office Hours: Tue 1:00-2:30 and Thu 2:00-3:00 in Rice 402
	- Prof Pettit Office Hours: Mon 2:30-4:00 and Wed 1:30-3:00 in Rice 212
	- TA office hours: Sunday through Thursday from 5 pm to 9 pm
	- Sun/Tue/Thu in Rice 032, Mon/Wed in Rice 540
- Today's lecture: [Dynamic Programming](dp.html)
:::



::: {.announcements}
# Tuesday, October 29th

- PS6 out, due Wednesday night
- PS7 out late this week, will be on DP
- PA3 out, due this Fri, Nov 1st
- Grading update
	- PS0, PS3, and PS4 have been returned
	- Regrades for the quizzes and PS3 & 4 will be opened until late this week
		- Use this responsibly!
	- Still to grade: regrades
- Office hours (reminder)
	- Prof Bloomfield Office Hours: Tue 1:00-2:30 and Thu 2:00-3:00 in Rice 402
	- Prof Pettit Office Hours: Mon 2:30-4:00 and Wed 1:30-3:00 in Rice 212
	- TA office hours: Sunday through Thursday from 5 pm to 9 pm
	- Sun/Tue/Thu in Rice 032, Mon/Wed in Rice 540
- Today's lecture: [Dynamic Programming](dp.html)
	- Warm-up: [matrix multiplication](dp.html#/warm-up-2)
:::
