---
title: "Announcements, Spring 2025"
---


## Warm-up (Feb 6)

<table><tr><td style="vertical-align:middle">

<table class="trominoes">
<tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td></td><td></td><td></td><td></td><td></td><td style="background:black"></td><td></td><td></td></tr>
<tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
</table>

</td><td>

<h4>Can you cover an 8x8 grid with 1 square missing using "trominoes"?</h4>

<p>&nbsp;</p>

<table><tr><td>Tromino:</td><td>
<table class="trominoes">
<tr><td style="background:blue"></td><td style="background:blue"></td></tr>
<tr style="border:none"><td style="border:none"></td><td style="border-bottom:2px solid black;background:blue"></td></tr>
</table>
</td></tr></table>

<p>&nbsp;</p>

<p><a href="https://nstarr.people.amherst.edu/trom/puzzle-8by8/">https://nstarr.people.amherst.edu/trom/puzzle-8by8/</a></p>

</td></tr></table>

::: {.announcements}
# Thursday, February 6th

- PS2 is was due yesterday -- how was it?
- PS3 will be out late this week
- PA1 is out
	- It's on Dijkstra's shorted path algorithm
	- Due date is Friday, February 14th
	- The submission will be up in a day or two
- Grading:
  - PS0 is graded and returned
  - PS1 is being graded (85% completed)
  - PS2 is going out to be graded today
- Office hours:
	- TA office hours are now in **Rice 109**
	- TA OH: M/Tu/W/Th from 5-9 in Olsson 009
	- Prof Bloomfield: M 10-11:30, W 1:30-3 in Rice 402 (note the change)
	- Prof Pettit: M 2:30-4:00, F 1:30-3:00 in Rice 212
- Course textbook link is on the Canvas landing page
- Today we start on divide and conquer, which will take 4-5 lectures
	- The slides are in Canvas' files
:::



::: {.announcements}
# Tuesday, February 4th

- PS2 is due tomorrow
- PA1 is out
	- It's on Dijkstra's shorted path algorithm
	- Due date is Friday, February 14th
- Office hours:
	- TA office hours are now in **Rice 109**
	- TA OH: M/Tu/W/Th from 5-9 in Olsson 009
	- Prof Bloomfield: M 10-11:30, W 1:30-3 in Rice 402 (note the change)
	- Prof Pettit: M 2:30-4:00, F 1:30-3:00 in Rice 212
- Course textbook link is on the Canvas landing page
- Today we continue (and likely finish) with graphs
	- This will take about 5 lectures total
	- The slides are in Canvas' files
:::



::: {.announcements}
# Thursday, January 30th

- PS1 was due yesterday
- PS2 will be out today, due next Wednesday
- PA1 will be out today
	- It's on Dijkstra's shorted path algorithm; we'll go over it today
	- Due date not yet set, but likely the week after next
- Office hours:
	- TA office hours are moving to **Rice 109**
	- TA OH: M/Tu/W/Th from 5-9 in Olsson 009
	- Prof Bloomfield: M 10-11:30, W 1:30-3 in Rice 402 (note the change)
	- Prof Pettit: M 2:30-4:00, F 1:30-3:00 in Rice 212
- Course textbook link is on the Canvas landing page
- Today we continue with graphs
	- This will take about ~~4~~ 5 lectures total
	- The slides are in Canvas' files
:::



::: {.announcements}
# Tuesday, January 28th

- PS1 will is due tomorrow by midnight
- PS2 will be out late this week
- PA1 is *almost* ready
	- It's on Dijkstra's shorted path algorithm
- Office hours:
	- TA OH: M/Tu/W/Th from 5-9 in Olsson 009
	  - We may add a Sunday shift
	- Prof Bloomfield: M 10-11:30, W 1:30-3 in Rice 402 (note the change)
	- Prof Pettit: M 2:30-4:00, F 1:30-3:00 in Rice 212
- Course textbook link is on the Canvas landing page
- Today we continue with graphs
	- This will take about 4 lectures total
	- The slides are in Canvas' files
:::


::: {.announcements}
# Thursday, January 23rd

- PS0 was due yesterday
- PS1 will be out today, due next Wednesday by midnight
- Office hours:
	- TA OH: M/Tu/W/Th from 5-9 in Olsson 009
	  - We may add a Sunday shift
	- Prof Bloomfield: M 9:30-11, W 1:30-3 in Rice 402 (note the change)
	- Prof Pettit: TBA in Rice 212
- Course textbook link is on the Canvas landing page
- Today we continue with graphs
	- This will take about 4 lectures total
	- The slides are in Canvas' files
:::



::: {.announcements}
# Tuesday, January 21st

- PS0 is due tomorrow (Wednesday, Jan 22) by 11:59 pm
	- It's in Canvas' assignments
	- Submit via Gradescope
- PS1 will be out late this week, due Wednesday of next week
- Office hours:
	- TA OH: M/Tu/W/Th from 5-9 in Olsson 009
	  - We may add a Sunday shift
	- Prof Bloomfield: M 9-11, W 2-3 in Rice 402
	- Prof Pettit: TBA in Rice 212
- Course textbook link is on the Canvas landing page
- Today we start graphs
	- This will take about 4 lectures
	- The slides are in Canvas' files
:::


::: {.announcements}
# Thursday, January 16th

- PS0 (out today) due next Wednesday (Jan 22) by 11:59 pm
	- It will be in Canvas' Assignments
- PS1 out next week, due the following Wednesday
- Course textbook link is on the Canvas landing page
- TA office hours coming soon (we are targeting Sun-Thu, 5pm-9pm)
- Prof. Bloomfield office hours TBA
- Prof. Pettit office hours TBA
:::

