meetingdays: TR 
labdays: X
firstday: 2026-08-25
lastday: 2026-12-08
holidays:
  - date: 2026-10-06
    name: Fall Reading Days
  - date: 2026-11-03
    name: Election Day
  - date: 2026-11-26
    name: Thanksgiving
exams:
assignments:
  - date: 2026-09-08
    name: Add deadline
  - date: 2026-09-17
    name: Practice Quiz (Wed-Fri)
  - date: 2026-10-08
    name: Graphs Quiz (Wed-Fri)
  - date: 2026-10-13
    name: Drop deadline
  - date: 2026-10-20
    name: Withdraw deadline
  - date: 2026-10-22
    name: Divide &amp; Conquer Quiz (Wed-Fri)
  - date: 2026-11-05
    name: Greedy Quiz (Wed-Fri)
  - date: 2026-11-19
    name: Dynamic Programming Quiz (Wed-Fri)
  - date: 2026-12-10
    name: Reductions Quiz (tbd)
  - date: 2026-09-08
    name: PS0 (LaTeX)

  - date: 2026-09-15
    name: PS1 (Graphs I)
  - date: 2026-09-22
    name: PS2 (Graphs II)
  - date: 2026-09-24
    name: PA1 (Graphs)

  - date: 2026-09-29
    name: PS3 (D&C I)
  - date: 2026-10-13
    name: PS4 (D&C II)
  - date: 2026-10-15
    name: PA2 (D&C)

  - date: 2026-10-20
    name: PS5 (Greedy I)
  - date: 2026-10-27
    name: PS6 (Greedy II)
  - date: 2026-10-29
    name: PA3 (Greedy)

  - date: 2026-11-10
    name: PS7 (DP I)
  - date: 2026-11-17
    name: PS8 (DP II)
  - date: 2026-11-24
    name: PA4 (DP)

  - date: 2026-12-01
    name: PS9 (Reductions I)
  - date: 2026-12-08
    name: PS10 (Reductions II)
  - date: 2026-12-08
    name: PA5 (Reductions)

labs:
